// AUTO-GENERATED BY ml/hb_estimator.js FOR ESP32-WROVER
// MEDIBOT Optical Non-Invasive Hemoglobin Calculation
#ifndef HB_ALGORITHM_H
#define HB_ALGORITHM_H

#include <Arduino.h>

// Calibration Weights
static const float HB_WEIGHT_BIAS = -32.574676f;
static const float HB_WEIGHT_INV_R = 37.438378f;
static const float HB_WEIGHT_R = 9.544445f;
static const float HB_WEIGHT_PI_IR = 0.007217f;
static const float HB_WEIGHT_RATIO_PI = 0.008786f;

enum AnemiaSeverity {
    ANEMIA_NONE = 0,       // >= 12.0 g/dL (Normal)
    ANEMIA_MILD = 1,       // 10.0 - 11.9 g/dL
    ANEMIA_MODERATE = 2,   // 7.0 - 9.9 g/dL
    ANEMIA_SEVERE = 3      // < 7.0 g/dL (Critical Emergency SOS)
};

struct HbResult {
    float hemoglobin_g_dl;
    float spo2_percent;
    float heart_rate_bpm;
    float r_ratio;
    float perfusion_index;
    AnemiaSeverity anemia_grade;
    bool valid;
};

inline const char* getAnemiaGradeHindi(AnemiaSeverity grade) {
    switch (grade) {
        case ANEMIA_NONE:     return "सामान्य (स्वस्थ)";
        case ANEMIA_MILD:     return "हल्का एनीमिया (Iron Supplements)";
        case ANEMIA_MODERATE: return "मध्यम एनीमिया (डॉक्टर जांच)";
        case ANEMIA_SEVERE:   return "गंभीर एनीमिया! (तत्काल PHC रिफर)";
        default:              return "अज्ञात";
    }
}

inline HbResult calculateHemoglobin(float ac_red, float dc_red, float ac_ir, float dc_ir, float heart_rate) {
    HbResult res;
    res.valid = false;

    // Safety checks: Avoid zero division and unplaced finger
    if (dc_red < 30000.0f || dc_ir < 30000.0f || ac_red < 50.0f || ac_ir < 50.0f) {
        return res; // Finger not detected or low signal quality
    }

    float pi_red = (ac_red / dc_red) * 100.0f;
    float pi_ir  = (ac_ir / dc_ir) * 100.0f;
    float r = (ac_red / dc_red) / (ac_ir / dc_ir);

    // Standard SpO2 computation
    float spo2 = 110.0f - 25.0f * r;
    if (spo2 > 100.0f) spo2 = 99.5f;
    if (spo2 < 70.0f) spo2 = 70.0f;

    // Empirical Multivariable Hemoglobin Estimation
    float inv_r = 1.0f / (r + 0.0001f);
    float ratio_pi = pi_red / (pi_ir + 0.0001f);

    float hb = HB_WEIGHT_BIAS +
               (HB_WEIGHT_INV_R * inv_r) +
               (HB_WEIGHT_R * r) +
               (HB_WEIGHT_PI_IR * pi_ir) +
               (HB_WEIGHT_RATIO_PI * ratio_pi);

    // Physiological bounds clamp (3.0 g/dL to 20.0 g/dL)
    if (hb < 3.0f) hb = 3.0f;
    if (hb > 20.0f) hb = 20.0f;

    res.hemoglobin_g_dl = hb;
    res.spo2_percent = spo2;
    res.heart_rate_bpm = heart_rate;
    res.r_ratio = r;
    res.perfusion_index = pi_ir;
    res.valid = true;

    // Categorize Anemia grade according to Indian Health Ministry Guidelines
    if (hb >= 12.0f) {
        res.anemia_grade = ANEMIA_NONE;
    } else if (hb >= 10.0f) {
        res.anemia_grade = ANEMIA_MILD;
    } else if (hb >= 7.0f) {
        res.anemia_grade = ANEMIA_MODERATE;
    } else {
        res.anemia_grade = ANEMIA_SEVERE;
    }

    return res;
}

#endif // HB_ALGORITHM_H
