/**
 * MEDIBOT - Non-Invasive Hemoglobin Calibration & C++ Exporter (Node.js)
 * ======================================================================
 * Runs with standard Node.js (no external npm dependencies required).
 * Simulates clinical PPG absorption, trains multivariate regression,
 * and exports `firmware/src/hb_algorithm.h`.
 */

const fs = require('fs');
const path = require('path');

function generateDataset(nSamples = 600) {
    const records = [];
    for (let i = 0; i < nSamples; i++) {
        // True Hb (6.5 to 16.5 g/dL)
        const hb_true = 6.5 + Math.random() * 10.0;
        
        // Photoplethysmography physics (Beer-Lambert ratio-of-ratios)
        const noise = (Math.random() - 0.5) * 0.4;
        const r_ratio = 0.55 + 6.5 / (hb_true + noise);
        
        const ac_red = 800 + Math.random() * 1700;
        const dc_red = 120000 + Math.random() * 60000;
        const pi_red = (ac_red / dc_red) * 100;
        
        const ac_ir = ac_red / (r_ratio * 0.95 + (Math.random() - 0.5) * 0.05);
        const dc_ir = 130000 + Math.random() * 60000;
        const pi_ir = (ac_ir / dc_ir) * 100;
        
        const hr = 60 + Math.random() * 40 + (14.0 - hb_true) * 1.5;
        
        records.push({
            hb_lab: hb_true,
            r_ratio: r_ratio,
            ac_red: ac_red,
            dc_red: dc_red,
            ac_ir: ac_ir,
            dc_ir: dc_ir,
            pi_red: pi_red,
            pi_ir: pi_ir,
            heart_rate: hr
        });
    }
    return records;
}

function trainModel(records) {
    // Linear System: Hb = w0 + w1*(1/R) + w2*R + w3*PI_IR + w4*(PI_Red / PI_IR)
    const n = records.length;
    const m = 5; // number of features
    
    // Build X matrix and y vector
    const X = [];
    const y = [];
    for (const r of records) {
        X.push([
            1.0,
            1.0 / (r.r_ratio + 1e-5),
            r.r_ratio,
            r.pi_ir,
            r.pi_red / (r.pi_ir + 1e-5)
        ]);
        y.push(r.hb_lab);
    }
    
    // Normal Equation with Ridge regularization: (X^T * X + lambda * I)^-1 * X^T * y
    const XT_X = Array.from({ length: m }, () => Array(m).fill(0));
    const XT_y = Array(m).fill(0);
    
    for (let i = 0; i < n; i++) {
        for (let j = 0; j < m; j++) {
            XT_y[j] += X[i][j] * y[i];
            for (let k = 0; k < m; k++) {
                XT_X[j][k] += X[i][j] * X[i][k];
            }
        }
    }
    
    // Add lambda to diagonal
    const lambda = 0.01;
    for (let j = 0; j < m; j++) {
        XT_X[j][j] += lambda;
    }
    
    // Gaussian Elimination with partial pivoting
    for (let i = 0; i < m; i++) {
        let maxRow = i;
        for (let k = i + 1; k < m; k++) {
            if (Math.abs(XT_X[k][i]) > Math.abs(XT_X[maxRow][i])) {
                maxRow = k;
            }
        }
        [XT_X[i], XT_X[maxRow]] = [XT_X[maxRow], XT_X[i]];
        [XT_y[i], XT_y[maxRow]] = [XT_y[maxRow], XT_y[i]];
        
        for (let k = i + 1; k < m; k++) {
            const factor = XT_X[k][i] / XT_X[i][i];
            XT_y[k] -= factor * XT_y[i];
            for (let j = i; j < m; j++) {
                XT_X[k][j] -= factor * XT_X[i][j];
            }
        }
    }
    
    const weights = Array(m).fill(0);
    for (let i = m - 1; i >= 0; i--) {
        let sum = 0;
        for (let j = i + 1; j < m; j++) {
            sum += XT_X[i][j] * weights[j];
        }
        weights[i] = (XT_y[i] - sum) / XT_X[i][i];
    }
    
    // Calculate MAE
    let totalError = 0;
    for (let i = 0; i < n; i++) {
        let pred = 0;
        for (let j = 0; j < m; j++) pred += X[i][j] * weights[j];
        totalError += Math.abs(pred - y[i]);
    }
    const mae = totalError / n;
    
    console.log("============================================================");
    console.log("🔬 MEDIBOT Non-Invasive Hemoglobin Calibration Results");
    console.log("============================================================");
    console.log(`Samples Trained    : ${n}`);
    console.log(`Mean Absolute Error: ${mae.toFixed(2)} g/dL (Target < 1.0 g/dL)`);
    console.log("Optimal Model Weights:");
    console.log(`  w0 (Bias)        : ${weights[0].toFixed(6)}`);
    console.log(`  w1 (1/R)         : ${weights[1].toFixed(6)}`);
    console.log(`  w2 (R)           : ${weights[2].toFixed(6)}`);
    console.log(`  w3 (PI_IR)       : ${weights[3].toFixed(6)}`);
    console.log(`  w4 (PI_Red/PI_IR): ${weights[4].toFixed(6)}`);
    console.log("============================================================");
    
    return weights;
}

function exportCppHeader(weights, outputPath) {
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
    
    const header = `// AUTO-GENERATED BY ml/hb_estimator.js FOR ESP32-WROVER
// MEDIBOT Optical Non-Invasive Hemoglobin Calculation
#ifndef HB_ALGORITHM_H
#define HB_ALGORITHM_H

#include <Arduino.h>

// Calibration Weights
static const float HB_WEIGHT_BIAS = ${weights[0].toFixed(6)}f;
static const float HB_WEIGHT_INV_R = ${weights[1].toFixed(6)}f;
static const float HB_WEIGHT_R = ${weights[2].toFixed(6)}f;
static const float HB_WEIGHT_PI_IR = ${weights[3].toFixed(6)}f;
static const float HB_WEIGHT_RATIO_PI = ${weights[4].toFixed(6)}f;

enum AnemiaSeverity {
    ANEMIA_NONE = 0,       // >= 12.0 g/dL (Normal)
    ANEMIA_MILD = 1,       // 10.0 - 11.9 g/dL
    ANEMIA_MODERATE = 2,   // 7.0 - 9.9 g/dL
    ANEMIA_SEVERE = 3      // < 7.0 g/dL (Critical Emergency SOS)
};

struct HbResult {
    float hemoglobin_g_dl;
    float spo2_percent;
    float heart_rate_bpm;
    float r_ratio;
    float perfusion_index;
    AnemiaSeverity anemia_grade;
    bool valid;
};

inline const char* getAnemiaGradeHindi(AnemiaSeverity grade) {
    switch (grade) {
        case ANEMIA_NONE:     return "सामान्य (स्वस्थ)";
        case ANEMIA_MILD:     return "हल्का एनीमिया (Iron Supplements)";
        case ANEMIA_MODERATE: return "मध्यम एनीमिया (डॉक्टर जांच)";
        case ANEMIA_SEVERE:   return "गंभीर एनीमिया! (तत्काल PHC रिफर)";
        default:              return "अज्ञात";
    }
}

inline HbResult calculateHemoglobin(float ac_red, float dc_red, float ac_ir, float dc_ir, float heart_rate) {
    HbResult res;
    res.valid = false;

    // Safety checks: Avoid zero division and unplaced finger
    if (dc_red < 30000.0f || dc_ir < 30000.0f || ac_red < 50.0f || ac_ir < 50.0f) {
        return res; // Finger not detected or low signal quality
    }

    float pi_red = (ac_red / dc_red) * 100.0f;
    float pi_ir  = (ac_ir / dc_ir) * 100.0f;
    float r = (ac_red / dc_red) / (ac_ir / dc_ir);

    // Standard SpO2 computation
    float spo2 = 110.0f - 25.0f * r;
    if (spo2 > 100.0f) spo2 = 99.5f;
    if (spo2 < 70.0f) spo2 = 70.0f;

    // Empirical Multivariable Hemoglobin Estimation
    float inv_r = 1.0f / (r + 0.0001f);
    float ratio_pi = pi_red / (pi_ir + 0.0001f);

    float hb = HB_WEIGHT_BIAS +
               (HB_WEIGHT_INV_R * inv_r) +
               (HB_WEIGHT_R * r) +
               (HB_WEIGHT_PI_IR * pi_ir) +
               (HB_WEIGHT_RATIO_PI * ratio_pi);

    // Physiological bounds clamp (3.0 g/dL to 20.0 g/dL)
    if (hb < 3.0f) hb = 3.0f;
    if (hb > 20.0f) hb = 20.0f;

    res.hemoglobin_g_dl = hb;
    res.spo2_percent = spo2;
    res.heart_rate_bpm = heart_rate;
    res.r_ratio = r;
    res.perfusion_index = pi_ir;
    res.valid = true;

    // Categorize Anemia grade according to Indian Health Ministry Guidelines
    if (hb >= 12.0f) {
        res.anemia_grade = ANEMIA_NONE;
    } else if (hb >= 10.0f) {
        res.anemia_grade = ANEMIA_MILD;
    } else if (hb >= 7.0f) {
        res.anemia_grade = ANEMIA_MODERATE;
    } else {
        res.anemia_grade = ANEMIA_SEVERE;
    }

    return res;
}

#endif // HB_ALGORITHM_H
`;

    fs.writeFileSync(outputPath, header, 'utf8');
    console.log(`✅ Exported Embedded C++ Header to: ${outputPath}`);
}

// Main execution
const dataset = generateDataset(600);
const weights = trainModel(dataset);
const headerPath = path.join(__dirname, '..', 'firmware', 'src', 'hb_algorithm.h');
exportCppHeader(weights, headerPath);

// Save mock CSV as well
const csvLines = ['hb_lab,r_ratio,ac_red,dc_red,ac_ir,dc_ir,pi_red,pi_ir,heart_rate'];
for (const r of dataset) {
    csvLines.push(`${r.hb_lab.toFixed(2)},${r.r_ratio.toFixed(4)},${r.ac_red.toFixed(1)},${r.dc_red.toFixed(1)},${r.ac_ir.toFixed(1)},${r.dc_ir.toFixed(1)},${r.pi_red.toFixed(3)},${r.pi_ir.toFixed(3)},${r.heart_rate.toFixed(1)}`);
}
fs.writeFileSync(path.join(__dirname, 'ppg_dataset_mock.csv'), csvLines.join('\n'), 'utf8');
console.log(`✅ Saved mock training dataset to ml/ppg_dataset_mock.csv`);
