; PlatformIO Project Configuration File for MEDIBOT Kiosk
[env:esp32-wrover-e]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D CORE_DEBUG_LEVEL=3

lib_deps = 
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2
    sandeepmistry/LoRa@^0.8.0
    miguelbalboa/MFRC522@^1.4.11
    bblanchon/ArduinoJson@^7.0.4
